'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZRK76lmlplq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Judson } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { useState } from 'react'
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import axios from "axios"
import { useRouter } from 'next/navigation'
import { Loader2 } from "lucide-react"
import { useToast } from "@/components/ui/use-toast"
import { z } from "zod"
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm, useFormState } from "react-hook-form"

import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"


export default function Signup() {
  const router = useRouter()
  const { toast } = useToast()

  const formSchema = z.object({
    email: z.string().email(),
    password: z.string().min(8),
    confirmPassword: z.string().min(8),
  })
  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      email: '',
      password: '',
      confirmPassword: ''
    },
  })

  const [isLoading, setIsLoading] = useState(false)

  async function onSubmit(values: z.infer<typeof formSchema>) {
    await signup(values)
  }

  const signup = async (values: z.infer<typeof formSchema>) => {
    console.log(form.formState.isSubmitSuccessful)
    setIsLoading(true)
    await axios.post('https://n8n.xponent.ph/webhook/api/auth/signup', values)
      .then(response => {

        if (response.data.error && typeof response.data.error === 'object') {
          setIsLoading(false);
          toast({
            title: 'Error',
            description: "Signup failed",
            variant: "destructive"
          });
          return;
        }
        if (response.data.statusCode === 200) {
          setIsLoading(false)
          toast({
            title: 'Success',
            description: "Signup successful",
          });
          router.push('/login')
        }

      })
      .catch(error => {
        setIsLoading(false);
        toast({
          title: 'Error',
          description: "Signup failed",
          variant: "destructive"
        });
      });
  }


  return (
    <div className="grid min-h-screen w-full grid-cols-1 md:grid-cols-2">
      <div className="flex flex-col items-center justify-center bg-primary p-6 md:p-12">
        <div className="max-w-md space-y-4">
          <div className="flex items-center space-x-2">
            <span className="text-2xl font-bold text-primary-foreground">26 Characters </span>
          </div>
          <p className="text-lg text-primary-foreground">
            Join the thousands of businesses that trust us to power their digital experiences.
          </p>
        </div>
      </div>
      <div className="flex items-center justify-center p-6 md:p-12">
        <div className="w-full max-w-md space-y-4">
          <h2 className="text-2xl font-bold">Create an account</h2>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
              <FormField
                control={form.control}
                name="email"
                render={({ field }) => (
                  <div className="space-y-1">
                    <FormLabel>Email</FormLabel>
                    <FormControl>
                      <Input id="email" type="email" placeholder="m@example.com" required {...field} />
                    </FormControl>
                  </div>
                )}
              />
              <FormField
                control={form.control}
                name="password"
                render={({ field }) => (
                  <div className="space-y-1">
                    <FormLabel>Password</FormLabel>
                    <FormControl>
                      <Input id="password" type="password" placeholder="Enter your password" required {...field} />
                    </FormControl>
                  </div>
                )}
              />
              <FormField
                control={form.control}
                name="confirmPassword"
                render={({ field }) => (
                  <div className="space-y-1">
                    <FormLabel>Confirm Password</FormLabel>
                    <FormControl>
                      <Input id="confirm-password" type="password" placeholder="Retype your password" required {...field} />
                    </FormControl>
                  </div>
                )}
              />
              <Button type="submit" className="w-full" disabled={form.formState.isSubmitting}>
                {form.formState.isSubmitting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}

                Sign Up
              </Button>
            </form>
          </Form>
          <div className="text-center text-sm text-muted-foreground">
            Already have an account?{" "}
            <Link href="/login" className="font-medium underline" prefetch={false}>
              Sign in
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}

